



    const data =[
        {
            id: 0,
            name: 'Cozy Modern Sofa',
            image: '/furniture1.png',
            des: 'A cozy, modern sofa perfect for any living room.',
            price: '700999',
        },
        {
            id: 1,
            name: 'Premium Fabric Upholstered Sofa',
            image: '/furniture2.png',
            des: 'Premium Fabric upholstery with ample seating and sleek design.',
            price: '250000',
        },
        {
            id: 2,
            name: 'Comfortable Contemporary Sofa',
            image: '/furniture3.png',
            des: 'A perfect blend of comfort and contemporary style, ideal for any living room.',
            price: '800000',
        },
        {
            id: 3,
            name: 'Stylish Comfortable Sofa',
            image: '/furniture4.png',
            des: 'A stylish, comfortable sofa that works in every living area.',
            price: '80999',
        },
        {
            id: 4,
            name: 'Sleek Modern Sofa',
            image: '/furniture5.png',
            des: 'Sleek and modern, offering stylish seating for smaller spaces.',
            price: '95000',
        },
        {
            id: 5,
            name: 'Premium Bed',
            image: '/furniture6.png',
            des: 'Experience unparalleled comfort and elegance every night.',
            price: '250000',
        },
        {
            id: 6,
            name: 'Stylish Chair',
            image: '/furniture7.png',
            des: 'Sleek and stylish, perfect for contemporary living rooms.',
            price: '200999',
        },
        {
            id: 7,
            name: 'Modern Bed',
            image: '/furniture8.png',
            des: 'Sleek, modern design with sturdy construction for a restful sleep.',
            price: '150000',
        },
        {
            id: 8,
            name: 'Contemporary Coffee Table',
            image: '/furniture9.png',
            des: 'A perfect blend of comfort and contemporary style, ideal for any living room.',
            price: '70000',
        },
        {
            id: 9,
            name: 'Luxury Premium Bed',
            image: '/furniture10.png',
            des: 'Experience unmatched comfort and elegance with our premium bed.',
            price: '650000',
        },
        {
            id: 10,
            name: 'Luxury Seating Bench',
            image: '/furniture11.png',
            des: 'Add a touch of luxury and extra seating to your bedroom.',
            price: '500000',
        },
        {
            id: 11,
            name: 'Elegant Media Console',
            image: '/furniture12.png',
            des: 'Ample storage and elegant design for all your media needs.',
            price: '170000',
        },
        {
            id: 12,
            name: 'Expandable Dining Table',
            image: '/furniture13.png',
            des: 'Perfect for family, this table extends to accommodate more guests.',
            price: '259999',
        },
        {
            id: 13,
            name: 'Simple Dining Set',
            image: '/furniture14.png',
            des: 'A lovely and straightforward dining set.',
            price: '400000',
        },
        {
            id: 14,
            name: 'Upholstered Dining Chairs',
            image: '/furniture15.png',
            des: 'Enjoy your meals in comfort with our elegantly upholstered dining chairs.',
            price: '800000',
        },
        {
            id: 15,
            name: 'Functional Office Desk',
            image: '/furniture16.png',
            des: 'A sleek and functional desk, perfect for any home office or study area.',
            price: '450999',
        },
        {
            id: 16,
            name: 'Ergonomic Office Chair',
            image: '/furniture17.png',
            des: 'Work comfortably with our ergonomically designed office chair.',
            price: '100000',
        },
        {
            id: 17,
            name: 'Comfortable Office Seats',
            image: '/furniture18.png',
            des: 'Ideal seats for a small office that are comfortable.',
            price: '700000',
        },
        {
            id: 18,
            name: 'Adjustable Outdoor Chair',
            image: '/furniture19.png',
            des: 'Relax and soak up the sun in our versatile, adjustable chair.',
            price: '450999',
        },
        {
            id: 19,
            name: 'Weather-Resistant Patio Sofa Set',
            image: '/furniture20.png',
            des: 'Enjoy the outdoors with our weather-resistant, comfortable patio sofa set.',
            price: '950000',
        },
        {
            id: 20,
            name: 'Outdoor Gathering Spot',
            image: '/furniture21.png',
            des: 'Create a cozy outdoor gathering spot for family and friends.',
            price: '600000',
        },
    ];
    
    export default data
